### ISSUE TITLE
crash when trying to open cell details

### ISSUE THREAD

**Issue by takiainen** [openbmap/android#93]
The app crashes when you select at "cells" tab any of the cells listed. Happens every time, regardless of ROM used. Currently I'm running slimsaber LP.

**Comment by wish7code** [comment]
Hey takiainen,

thanks for reporting. The issue has been fixed with https://github.com/wish7code/openbmap/commit/9b28c3c5da4025a874fbdb651ae82f47dffa9105 . Unfortunately we still have some minor remaining issues, so we haven't yet updated the F-Droid release.

I leave this issue open till the new F-Droid release is there..

Cheers
Toby
